version: 2
jobs:
  build:
    working_directory: &work_dir /usr/local/go/src/github.com/cloudcloud/go-id3
    docker:
      - image: cloudcloud/golang:1.11
    environment: &environment
    steps:
      - run:
          name: Checkout Code
          command: |
            # Checking out to the current working directory
            git clone https://github.com/cloudcloud/go-id3.git .
            mkdir -p /tmp/artifacts
      - run:
          name: Run Tests
          command: |
            set -eou pipefail
            go test -race ./...
      - run:
          name: Artifact Binary
          command: |
            go install ./...
            mv `which go-id3` /tmp/artifacts/go-id3
      - run:
          name: Setup CodeClimate Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Coverage Commands
          command: |
            go test -race -coverprofile=c.out -covermode=atomic ./...
            go tool cover -html=c.out -o ./coverage.html
            cp c.out /tmp/artifacts
            cp cov* /tmp/artifacts
      - run:
          name: CodeCov Upload
          command: bash <(curl -s https://codecov.io/bash) -f c.out
      - run:
          name: CodeClimate Upload
          command: |
            sed -i s#github.com/cloudcloud/go-id3/## c.out
            ./cc-test-reporter after-build -t gocov --exit-code $?
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  go-id3:
    jobs:
      - build
