package frames

var (
	// Version22Frames defines the version 2.2 frame mapping
	// http://id3.org/id3v2-00
	Version22Frames = map[string]func() IFrame{
		"BUF": Gen("BUF", "Recommended buffer size", Version2),
		"CNT": Gen("CNT", "Play counter", Version2),
		"COM": Gen("COM", "Comments", Version2),
		"CRA": Gen("CRA", "Audio encryption", Version2),
		"CRM": Gen("CRM", "Encrypted meta frame", Version2),
		"ETC": Gen("ETC", "Event timing codes", Version2),
		"EQU": Gen("EQU", "Equalization", Version2),
		"GEO": Gen("GEO", "General encapsulated object", Version2),
		"IPL": Gen("IPL", "Involved people list", Version2),
		"LNK": Gen("LNK", "Linked information", Version2),
		"MCI": Gen("MCI", "Music CD identifier", Version2),
		"MLL": Gen("MLL", "MPEG location lookup table", Version2),
		"PIC": Gen("PIC", "Attached picture", Version2),
		"POP": Gen("POP", "Popularimeter", Version2),
		"REV": Gen("REV", "Reverb", Version2),
		"RVA": Gen("RVA", "Relative volume adjustment", Version2),
		"SLT": Gen("SLT", "Synchronized lyric/text", Version2),
		"STC": Gen("STC", "Synched tempo codes", Version2),
		"TAL": Gen("TAL", "Album/Movie/Show title", Version2),
		"TBP": Gen("TBP", "BPM (Beats Per Minute)", Version2),
		"TCM": Gen("TCM", "Composer", Version2),
		"TCO": Gen("TCO", "Content type", Version2),
		"TCR": Gen("TCR", "Copyright message", Version2),
		"TDA": Gen("TDA", "Date", Version2),
		"TDY": Gen("TDY", "Playlist delay", Version2),
		"TEN": Gen("TEN", "Encoded by", Version2),
		"TFT": Gen("TFT", "File type", Version2),
		"TIM": Gen("TIM", "Time", Version2),
		"TKE": Gen("TKE", "Initial key", Version2),
		"TLA": Gen("TLA", "Language(s)", Version2),
		"TLE": Gen("TLE", "Length", Version2),
		"TMT": Gen("TMT", "Media type", Version2),
		"TOA": Gen("TOA", "Original artist(s)/performer(s)", Version2),
		"TOF": Gen("TOF", "Original filename", Version2),
		"TOL": Gen("TOL", "Original Lyricist(s)/text writer(s)", Version2),
		"TOR": Gen("TOR", "Original release year", Version2),
		"TOT": Gen("TOT", "Original album/Movie/Show title", Version2),
		"TP1": Gen("TP1", "Lead artist(s)/Lead performer(s)/Soloist(s)/Performing group", Version2),
		"TP2": Gen("TP2", "Band/Orchestra/Accompaniment", Version2),
		"TP3": Gen("TP3", "Conductor/Performer refinement", Version2),
		"TP4": Gen("TP4", "Interpreted, remixed, or otherwise modified by", Version2),
		"TPA": Gen("TPA", "Part of a set", Version2),
		"TPB": Gen("TPB", "Publisher", Version2),
		"TRC": Gen("TRC", "ISRC (International Standard Recording Code)", Version2),
		"TRD": Gen("TRD", "Recording dates", Version2),
		"TRK": Gen("TRK", "Track number/Position in set", Version2),
		"TSI": Gen("TSI", "Size", Version2),
		"TSS": Gen("TSS", "Software/hardware and settings used for encoding", Version2),
		"TT1": Gen("TT1", "Content group description", Version2),
		"TT2": Gen("TT2", "Title/Songname/Content description", Version2),
		"TT3": Gen("TT3", "Subtitle/Description refinement", Version2),
		"TXT": Gen("TXT", "Lyricist/text writer", Version2),
		"TXX": Gen("TXX", "User defined text information frame", Version2),
		"TYE": Gen("TYE", "Year", Version2),
		"UFI": Gen("UFI", "Unique file identifier", Version2),
		"ULT": Gen("ULT", "Unsynchronized lyric/text transcription", Version2),
		"WAF": Gen("WAF", "Official audio file webpage", Version2),
		"WAR": Gen("WAR", "Official artist/performer webpage", Version2),
		"WAS": Gen("WAS", "Official audio source webpage", Version2),
		"WCM": Gen("WCM", "Commercial information", Version2),
		"WCP": Gen("WCP", "Copyright/Legal information", Version2),
		"WPB": Gen("WPB", "Publishers official webpage", Version2),
		"WXX": Gen("WXX", "User defined URL link frame", Version2),
	}
)
