package frames

var (
	// Version24Frames defines the version 2.4 frame mapping
	// http://id3.org/id3v2.4.0-frames
	Version24Frames = map[string]func() IFrame{
		"AENC": Gen("AENC", "Audio encryption", Version4),
		"APIC": Gen("APIC", "Attached picture", Version4),
		"ASPI": Gen("ASPI", "Audio seek point index", Version4),
		"COMM": Gen("COMM", "Comments", Version4),
		"COMR": Gen("COMR", "Commercial frame", Version4),
		"ENCR": Gen("ENCR", "Encryption method registration", Version4),
		"EQUA": Gen("EQUA", "Equalization", Version4),
		"EQU2": Gen("EQU2", "Equalisation (2)", Version4),
		"ETCO": Gen("ETCO", "Event timing codes", Version4),
		"GEOB": Gen("GEOB", "General encapsulated object", Version4),
		"GRID": Gen("GRID", "Group registration identifier", Version4),
		"IPLS": Gen("IPLS", "Involved people list", Version4),
		"LINK": Gen("LINK", "Linked information", Version4),
		"MCDI": Gen("MCDI", "Music CD identifier", Version4),
		"MLLT": Gen("MLLT", "MPEG location lookup table", Version4),
		"OWNE": Gen("OWNE", "Ownership frame", Version4),
		"PRIV": Gen("PRIV", "Private frame", Version4),
		"PCNT": Gen("PCNT", "Play counter", Version4),
		"POPM": Gen("POPM", "Popularimeter", Version4),
		"POSS": Gen("POSS", "Position synchronisation frame", Version4),
		"RBUF": Gen("RBUF", "Recommended buffer size", Version4),
		"RVAD": Gen("RVAD", "Relative volume adjustment", Version4),
		"RVA2": Gen("RVA2", "Relative volume adjustment (2)", Version4),
		"RVRB": Gen("RVRB", "Reverb", Version4),
		"SEEK": Gen("SEEK", "Seek frame", Version4),
		"SIGN": Gen("SIGN", "Signature frame", Version4),
		"SYLT": Gen("SYLT", "Synchronised lyric/text", Version4),
		"SYTC": Gen("SYTC", "Synchronised tempo codes", Version4),
		"TALB": Gen("TALB", "Album/Movie/Show title", Version4),
		"TBPM": Gen("TBPM", "BPM (beats per minute)", Version4),
		"TCOM": Gen("TCOM", "Composer", Version4),
		"TCON": Gen("TCON", "Content type", Version4),
		"TCOP": Gen("TCOP", "Copyright message", Version4),
		"TDAT": Gen("TDAT", "Date", Version4),
		"TDEN": Gen("TDEN", "Encoding time", Version4),
		"TDLY": Gen("TDLY", "Playlist delay", Version4),
		"TDOR": Gen("TDOR", "Original release time", Version4),
		"TDRC": Gen("TDRC", "Recording time", Version4),
		"TDRL": Gen("TDRL", "Release time", Version4),
		"TDTG": Gen("TDTG", "Tagging time", Version4),
		"TENC": Gen("TENC", "Encoded by", Version4),
		"TEXT": Gen("TEXT", "Lyricist/Text writer", Version4),
		"TFLT": Gen("TFLT", "File type", Version4),
		"TIME": Gen("TIME", "Time", Version4),
		"TIPL": Gen("TIPL", "Involved people list", Version4),
		"TIT1": Gen("TIT1", "Content group description", Version4),
		"TIT2": Gen("TIT2", "Title/songname/content description", Version4),
		"TIT3": Gen("TIT3", "Subtitle/Description refinement", Version4),
		"TKEY": Gen("TKEY", "Initial key", Version4),
		"TLAN": Gen("TLAN", "Language(s)", Version4),
		"TLEN": Gen("TLEN", "Length", Version4),
		"TMCL": Gen("TMCL", "Musician credits list", Version4),
		"TMED": Gen("TMED", "Media type", Version4),
		"TMOO": Gen("TMOO", "Mood", Version4),
		"TOAL": Gen("TOAL", "Original album/movie/show title", Version4),
		"TOFN": Gen("TOFN", "Original filename", Version4),
		"TOLY": Gen("TOLY", "Original lyricist(s)/text writer(s)", Version4),
		"TOPE": Gen("TOPE", "Original artist(s)/performer(s)", Version4),
		"TORY": Gen("TORY", "Original release year", Version4),
		"TOWN": Gen("TOWN", "File owner/licensee", Version4),
		"TPE1": Gen("TPE1", "Lead performer(s)/Soloist(s)", Version4),
		"TPE2": Gen("TPE2", "Band/orchestra/accompaniment", Version4),
		"TPE3": Gen("TPE3", "Conductor/performer refinement", Version4),
		"TPE4": Gen("TPE4", "Interpreted, remixed, or otherwise modified by", Version4),
		"TPOS": Gen("TPOS", "Part of a set", Version4),
		"TPRO": Gen("TPRO", "Produced notice", Version4),
		"TPUB": Gen("TPUB", "Publisher", Version4),
		"TRCK": Gen("TRCK", "Track number/Position in set", Version4),
		"TRDA": Gen("TRDA", "Recording dates", Version4),
		"TRSN": Gen("TRSN", "Internet radio station name", Version4),
		"TRSO": Gen("TRSO", "Internet radio station owner", Version4),
		"TSIZ": Gen("TSIZ", "Size", Version4),
		"TSOA": Gen("TSOA", "Album sort order", Version4),
		"TSOP": Gen("TSOP", "Performer sort order", Version4),
		"TSOT": Gen("TSOT", "Title sort order", Version4),
		"TSRC": Gen("TSRC", "ISRC (international standard recording code)", Version4),
		"TSSE": Gen("TSSE", "Software/Hardware and settings used for encoding", Version4),
		"TSST": Gen("TSST", "Set subtitle", Version4),
		"TYER": Gen("TYER", "Year", Version4),
		"TXXX": Gen("TXXX", "User defined text information frame", Version4),
		"UFID": Gen("TYER", "Year", Version4),
		"USER": Gen("USER", "Terms of use", Version4),
		"USLT": Gen("USLT", "Unsynchronised lyric/text transcription", Version4),
		"WCOM": Gen("WCOM", "Commercial information", Version4),
		"WCOP": Gen("WCOP", "Copyright/Legal information", Version4),
		"WOAF": Gen("WOAF", "Official audio file webpage", Version4),
		"WOAR": Gen("WOAR", "Official artist/performer webpage", Version4),
		"WOAS": Gen("WOAS", "Official audio source webpage", Version4),
		"WORS": Gen("WORS", "Official Internet radio station homepage", Version4),
		"WPAY": Gen("WPAY", "Payment", Version4),
		"WPUB": Gen("WPUB", "Publishers official webpage", Version4),
		"WXXX": Gen("WXXX", "User defined URL link frame", Version4),
	}
)
